<#
.SYNOPSIS
    Disable the internal logs generated by all OpenTelemetry components.
.DESCRIPTION
    Remove the `OTEL_DIAGNOSTICS.json` file to disabled the internal logs generated by all OpenTelemetry components.
.LINK
    Enable-OtelDiagnosticLog
.EXAMPLE
    Disable-OtelDiagnosticLog

    Disable the internal logs.
#>
function Disable-OtelDiagnosticLog {
    [CmdletBinding()]
    param ()

    $name = 'OTEL_DIAGNOSTICS.json'
    $path = Join-Path -Path ([System.IO.Directory]::GetCurrentDirectory()) -ChildPath $name

    Remove-Item -Path $path
}